# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BitpandaChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BitpandaChallenge

  pod 'SVGKit'


  target 'BitpandaChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BitpandaChallengeUITests' do
    # Pods for testing
  end

end
